/**
 * Init Command - Interactive Configuration Wizard
 * 
 * Creates i18n.config.json and .env files through an interactive CLI wizard.
 */

import { existsSync, writeFileSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createPromptModule } from 'inquirer';
import { colors, createSpinner, printHeader } from '../cli/ui.js';
import { getLanguageDisplayName, getLanguageChoices } from '../languages.js';

// Create inquirer prompt instance with all prompt types
const prompts = createPromptModule().prompts;
const { input, password, select, checkbox, confirm } = prompts;

// ============================================================================
// CONSTANTS
// ============================================================================

const LLM_PROVIDERS = [
  { 
    name: 'DeepSeek (Recommended - Best value)', 
    value: { baseURL: 'https://api.deepseek.com', model: 'deepseek-chat' } 
  },
  { 
    name: 'OpenAI (GPT-4o-mini)', 
    value: { baseURL: 'https://api.openai.com/v1', model: 'gpt-4o-mini' } 
  },
  { 
    name: 'OpenAI (GPT-4o)', 
    value: { baseURL: 'https://api.openai.com/v1', model: 'gpt-4o' } 
  },
  { 
    name: 'Azure OpenAI', 
    value: { baseURL: '', model: '', isCustom: true } 
  },
  { 
    name: 'Ollama (Local)', 
    value: { baseURL: 'http://localhost:11434/v1', model: 'llama3' } 
  },
  { 
    name: 'Custom Provider', 
    value: { baseURL: '', model: '', isCustom: true } 
  },
];

const DEFAULT_SYSTEM_PROMPT = `You are a professional translator specializing in software localization.

Your task is to translate Angular i18n messages from one language to another while:
1. Preserving all placeholders like {0}, {1}, {count}, etc.
2. Maintaining ICU message format for plurals and selections
3. Keeping HTML tags and entities intact
4. Adapting tone and formality to match the target culture
5. Translating in context, considering this is UI text

Provide only the translation without explanations or additional text.`;

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Build language config entries
 */
function buildLanguageConfig(sourceLanguage, targetLanguages) {
  const languages = [
    { 
      code: sourceLanguage, 
      name: getLanguageDisplayName(sourceLanguage), 
      file: `messages.${sourceLanguage}.xlf` 
    }
  ];
  
  for (const targetCode of targetLanguages) {
    languages.push({
      code: targetCode,
      name: getLanguageDisplayName(targetCode),
      file: `messages.${targetCode}.xlf`
    });
  }
  
  return languages;
}

/**
 * Generate i18n.config.json content
 */
function generateConfig(languages, sourceLanguage, batchSettings) {
  return {
    languages,
    sourceLanguage,
    sourceFile: 'messages.xlf',
    csvOutput: 'messages.csv',
    outputDir: 'dist-i18n',
    batchDir: 'batches',
    llm: {
      baseURL: '${LLM_BASE_URL}',
      apiKey: '${LLM_API_KEY}',
      model: '${LLM_MODEL}',
      batchSize: batchSettings.batchSize,
      concurrency: batchSettings.concurrency,
      systemPrompt: DEFAULT_SYSTEM_PROMPT
    }
  };
}

/**
 * Generate .env content
 */
function generateEnv(apiKey, baseURL, model) {
  let content = `# Angular i18n Translator Configuration
# Generated by 'init' command

LLM_API_KEY=${apiKey}
LLM_BASE_URL=${baseURL}
LLM_MODEL=${model}
`;
  return content;
}

/**
 * Check if .env exists and merge API key
 */
function updateEnvFile(envPath, apiKey, baseURL, model) {
  let content = '';
  
  if (existsSync(envPath)) {
    content = readFileSync(envPath, 'utf-8');
    
    // Update or add each variable
    const updates = [
      { key: 'LLM_API_KEY', value: apiKey },
      { key: 'LLM_BASE_URL', value: baseURL },
      { key: 'LLM_MODEL', value: model }
    ];
    
    for (const { key, value } of updates) {
      const regex = new RegExp(`^${key}=.*$`, 'm');
      if (regex.test(content)) {
        content = content.replace(regex, `${key}=${value}`);
      } else {
        // Add to end if not present
        content += `\n${key}=${value}`;
      }
    }
  } else {
    content = generateEnv(apiKey, baseURL, model);
  }
  
  return content;
}

// ============================================================================
// WIZARD STEPS
// ============================================================================

/**
 * Step 1: Ask for API Key
 */
async function askApiKey() {
  const apiKey = await password({
    message: 'Enter your LLM API key',
    mask: '*',
    validate: (value) => {
      if (!value || value.trim().length === 0) {
        return 'API key is required';
      }
      return true;
    }
  });
  
  return apiKey.trim();
}

/**
 * Step 2: Select LLM Provider
 */
async function askProvider() {
  const provider = await select({
    message: 'Select your LLM provider',
    choices: LLM_PROVIDERS,
    pageSize: 8
  });
  
  return provider;
}

/**
 * Step 3: Ask for custom URL and model (if needed)
 */
async function askCustomProviderConfig(provider) {
  if (!provider.isCustom) {
    return provider;
  }
  
  console.log();
  
  const baseURL = await input({
    message: 'Enter API base URL',
    validate: (value) => {
      if (!value || value.trim().length === 0) {
        return 'URL is required';
      }
      if (!value.startsWith('http://') && !value.startsWith('https://')) {
        return 'URL must start with http:// or https://';
      }
      return true;
    }
  });
  
  const model = await input({
    message: 'Enter model name',
    validate: (value) => {
      if (!value || value.trim().length === 0) {
        return 'Model name is required';
      }
      return true;
    }
  });
  
  return { baseURL: baseURL.trim(), model: model.trim() };
}

/**
 * Step 4: Select Source Language
 */
async function askSourceLanguage() {
  const sourceLanguage = await select({
    message: 'Select source language (the language of your original XLF file)',
    choices: getLanguageChoices(),
    pageSize: 10
  });
  
  return sourceLanguage;
}

/**
 * Step 5: Select Target Languages
 */
async function askTargetLanguages(sourceLanguage) {
  const availableTargets = getLanguageChoices().filter(l => l.value !== sourceLanguage);
  
  const targetLanguages = await checkbox({
    message: 'Select target languages (languages to translate TO)',
    choices: availableTargets,
    pageSize: 12,
    validate: (choices) => {
      if (!choices || choices.length === 0) {
        return 'Please select at least one target language';
      }
      return true;
    }
  });
  
  return targetLanguages;
}

/**
 * Step 6: Batch Settings (optional)
 */
async function askBatchSettings() {
  const customizeBatch = await confirm({
    message: 'Customize batch settings?',
    default: false
  });
  
  if (!customizeBatch) {
    return { batchSize: 50, concurrency: 5 };
  }
  
  console.log();
  
  const batchSizeInput = await input({
    message: 'Records per batch',
    default: '50',
    validate: (value) => {
      const num = parseInt(value, 10);
      if (isNaN(num) || num < 1) {
        return 'Must be a positive number';
      }
      if (num > 200) {
        return 'Batch size should not exceed 200 for best results';
      }
      return true;
    }
  });
  
  const concurrencyInput = await input({
    message: 'Concurrent batches per language',
    default: '5',
    validate: (value) => {
      const num = parseInt(value, 10);
      if (isNaN(num) || num < 1) {
        return 'Must be a positive number';
      }
      if (num > 20) {
        return 'Concurrency should not exceed 20 to avoid rate limits';
      }
      return true;
    }
  });
  
  return {
    batchSize: parseInt(batchSizeInput, 10),
    concurrency: parseInt(concurrencyInput, 10)
  };
}

/**
 * Step 7: Summary and confirmation
 */
async function showSummary(config, envPath, configPath) {
  console.log();
  console.log(colors.highlight('━━━ Configuration Summary ━━━'));
  console.log();
  
  console.log(`${colors.dim('API Key:')} ${colors.success('***configured***')}`);
  console.log(`${colors.dim('Base URL:')} ${colors.info(config.llm.baseURL)}`);
  console.log(`${colors.dim('Model:')} ${colors.info(config.llm.model)}`);
  console.log();
  
  console.log(`${colors.dim('Source Language:')} ${colors.highlight(getLanguageDisplayName(config.sourceLanguage))}`);
  console.log(`${colors.dim('Target Languages:')}`);
  for (const lang of config.languages) {
    if (lang.code !== config.sourceLanguage) {
      console.log(`  • ${lang.name}`);
    }
  }
  console.log();
  
  console.log(`${colors.dim('Batch Size:')} ${colors.number(config.llm.batchSize)}`);
  console.log(`${colors.dim('Concurrency:')} ${colors.number(config.llm.concurrency)}`);
  console.log();
  
  console.log(`${colors.dim('Files to create:')}`);
  console.log(`  • ${colors.path(envPath)}`);
  console.log(`  • ${colors.path(configPath)}`);
  console.log();
  
  const confirmCreate = await confirm({
    message: 'Create configuration files?',
    default: true
  });
  
  return confirmCreate;
}

/**
 * Show next steps
 */
function showNextSteps() {
  console.log();
  console.log(colors.highlight('━━━ Next Steps ━━━'));
  console.log();
  console.log('1. Place your source XLF file as:');
  console.log(`   ${colors.path('messages.xlf')}`);
  console.log();
  console.log('2. Run the full translation pipeline:');
  console.log(`   ${colors.highlight('npm run translate:all')}`);
  console.log();
  console.log('   Or run individual steps:');
  console.log(`   ${colors.dim('npm run xlf-to-csv')}    - Convert XLF to CSV`);
  console.log(`   ${colors.dim('npm run translate:split')} - Split into batches`);
  console.log(`   ${colors.dim('npm run translate:run')}  - Run LLM translation`);
  console.log(`   ${colors.dim('npm run translate:merge')} - Merge translations`);
  console.log(`   ${colors.dim('npm run csv-to-xlf')}    - Convert back to XLF`);
  console.log();
  console.log('3. Find translated XLF files in:');
  console.log(`   ${colors.path('dist-i18n/')}`);
  console.log();
}

// ============================================================================
// MAIN HANDLER
// ============================================================================

/**
 * Main init command handler
 */
async function handleInit() {
  printHeader('Interactive Configuration Wizard');
  
  const cwd = process.cwd();
  const envPath = resolve(cwd, '.env');
  const configPath = resolve(cwd, 'i18n.config.json');
  
  // Check for existing config
  if (existsSync(configPath)) {
    console.log(colors.warning('⚠ An i18n.config.json file already exists.'));
    const overwrite = await confirm({
      message: 'Do you want to overwrite it?',
      default: false
    });
    
    if (!overwrite) {
      console.log(colors.dim('Configuration cancelled.'));
      return 0;
    }
  }
  
  console.log(colors.dim('This wizard will help you set up your i18n translation configuration.\n'));
  
  // Step 1: API Key
  const apiKey = await askApiKey();
  
  // Step 2: LLM Provider
  const providerSelection = await askProvider();
  
  // Step 3: Custom config if needed
  const provider = await askCustomProviderConfig(providerSelection);
  
  // Step 4: Source Language
  const sourceLanguage = await askSourceLanguage();
  
  // Step 5: Target Languages
  const targetLanguages = await askTargetLanguages(sourceLanguage);
  
  // Step 6: Batch Settings
  const batchSettings = await askBatchSettings();
  
  // Build configuration
  const languages = buildLanguageConfig(sourceLanguage, targetLanguages);
  const config = generateConfig(languages, sourceLanguage, batchSettings);
  
  // Replace placeholders for display (actual config uses env vars)
  const displayConfig = {
    ...config,
    llm: {
      ...config.llm,
      baseURL: provider.baseURL,
      apiKey: '***',
      model: provider.model
    }
  };
  
  // Step 7: Summary and confirmation
  const confirmed = await showSummary(displayConfig, envPath, configPath);
  
  if (!confirmed) {
    console.log(colors.dim('\nConfiguration cancelled.'));
    return 0;
  }
  
  // Create files
  const spinner = createSpinner('Creating configuration files...');
  spinner.start();
  
  try {
    // Update/create .env file
    const envContent = updateEnvFile(envPath, apiKey, provider.baseURL, provider.model);
    writeFileSync(envPath, envContent, 'utf-8');
    
    // Create i18n.config.json
    const configJson = JSON.stringify(config, null, 2);
    writeFileSync(configPath, configJson, 'utf-8');
    
    spinner.succeed('Configuration files created successfully!');
    
    // Add .env to .gitignore if not present
    const gitignorePath = resolve(cwd, '.gitignore');
    if (existsSync(gitignorePath)) {
      const gitignore = readFileSync(gitignorePath, 'utf-8');
      if (!gitignore.includes('.env')) {
        const updatedGitignore = gitignore.trimEnd() + '\n\n# Environment variables\n.env\n';
        writeFileSync(gitignorePath, updatedGitignore, 'utf-8');
        console.log(colors.success('✓ Added .env to .gitignore'));
      }
    }
    
    // Show success message and next steps
    console.log();
    console.log(colors.success('✓ Configuration complete!'));
    
    showNextSteps();
    
    return 0;
  } catch (error) {
    spinner.fail(`Failed to create configuration: ${error.message}`);
    return 1;
  }
}

export default handleInit;
